"use client";
import React, { useEffect, useState } from "react";
import { UsersIcon, SearchIcon, FilterIcon, DownloadIcon } from "lucide-react";
import Link from "next/link";
import { useLecturerDashboard } from "../context/lecturerContext";
import { LecturerCourse } from "@/app/types";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import toast from "react-hot-toast";

export default function page() {
  const [searchTerm, setSearchTerm] = useState("");
  const [filter, setFilter] = useState("all");
  const [selectedCourse, setSelectedCourse] = useState("all");
  const { lecturerCourses, setShouldRefresh } = useLecturerDashboard();

  useEffect(() => {
    console.log(lecturerCourses);
  }, []);

  // Calculate engagement and progress for a student in a course
  function calculateMetrics(student: any, course: LecturerCourse) {
    const totalLectures = course.lectures.length;

    if (totalLectures === 0) {
      return { progress: 0, engagement: 0 };
    }

    // Progress = watched lectures / total lectures
    const watchedLectures = course.lectures.filter((lecture) =>
      student.lectureProgresses.some(
        (p: any) => p.lectureId === lecture.id && p.watched
      )
    ).length;

    const progress = Math.round((watchedLectures / totalLectures) * 100);

    // Engagement = average engagement score across attended lectures
    const lectureLogs = course.lectures.flatMap((lecture) =>
      lecture.attendanceLogs.filter((log) => log.userId === student.id)
    );

    let engagement = 0;
    if (lectureLogs.length > 0) {
      engagement = Math.round(
        lectureLogs.reduce((sum, log) => sum + (log.engagementScore || 0), 0) /
          lectureLogs.length
      );
    }

    return { progress, engagement };
  }

  const students = lecturerCourses.flatMap((course) =>
    course.enrollments.map((enrollment) => {
      const user = enrollment.user;
      const { progress, engagement } = calculateMetrics(user, course);

      return {
        ...user,
        courseId: course.id,
        courseTitle: course.title,
        progress,
        engagement,
      };
    })
  );

  // Filter students based on search term, filter, and selected course
  const filteredStudents = students.filter((student) => {
    const matchesSearch =
      student.firstName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      student.email.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesCourse =
      selectedCourse === "all" || student.courseId === parseInt(selectedCourse);

    if (filter === "all") return matchesSearch && matchesCourse;
    if (filter === "high-engagement")
      return matchesSearch && matchesCourse && student.engagement >= 90;
    if (filter === "low-engagement")
      return matchesSearch && matchesCourse && student.engagement < 75;
    return matchesSearch && matchesCourse;
  });

  const handleExportPDF = () => {
    if (!filteredStudents || filteredStudents.length === 0) {
      alert("No student data available to export.");
      return;
    }

    try {
      const doc = new jsPDF();

      // Title
      doc.setFontSize(16);
      const title =
        selectedCourse && selectedCourse !== "all"
          ? `Student Report - ${selectedCourse}`
          : "Student Report - All Courses";
      doc.text(title, 14, 20);

      // Build table
      const tableColumn = [
        "Name",
        "Email",
        "Course",
        "Progress (%)",
        "Engagement (%)",
      ];
      const tableRows = filteredStudents.map((student) => [
        `${student.firstName} ${student.lastName}`,
        student.email,
        student.courseTitle,
        `${student.progress}%`,
        `${student.engagement}%`,
      ]);

      // AutoTable
      autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 30,
        styles: { fontSize: 10 },
        headStyles: { fillColor: [0, 123, 255] },
      });

      // Footer
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(10);
      doc.text("Generated by Lecturer Dashboard", 14, pageHeight - 10);

      // Save
      const fileName =
        selectedCourse && selectedCourse !== "all"
          ? `student-report-${selectedCourse}.pdf`
          : "student-report-all.pdf";

      doc.save(fileName);
      toast.success("PDF report generated successfully!");
    } catch (error) {
      console.log("Error generating PDF:", error);
      toast.error(
        "An error occurred while generating the PDF. Please try again."
      );
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <h1 className="text-2xl font-bold text-gray-900">Students</h1>
        <button
          onClick={handleExportPDF}
          className="cursor-pointer flex items-center gap-1 px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 sm:ml-auto"
        >
          <DownloadIcon className="w-4 h-4" />
          <span>Export Report as PDF</span>
        </button>
      </div>
      <div className="bg-white rounded-xl shadow-sm">
        <div className="p-6 border-b border-gray-200">
          <div className="flex flex-col sm:flex-row gap-4 items-center justify-between">
            <div className="flex items-center gap-2 w-full sm:w-auto">
              <UsersIcon className="w-5 h-5 text-gray-500" />
              <h2 className="text-lg font-semibold text-gray-900">
                Enrolled Students
              </h2>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
              <div className="relative w-full sm:w-auto">
                <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5" />
                <input
                  type="search"
                  placeholder="Search students..."
                  className="pl-10 pr-4 py-2 border border-gray-200 rounded-lg w-full"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
              <div className="relative w-full sm:w-auto">
                <FilterIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5" />
                <select
                  value={filter}
                  onChange={(e) => setFilter(e.target.value)}
                  className="pl-10 pr-4 py-2 border border-gray-200 rounded-lg appearance-none bg-white w-full"
                >
                  <option value="all">All Students</option>
                  <option value="high-engagement">High Engagement</option>
                  <option value="low-engagement">Low Engagement</option>
                </select>
              </div>
              <div className="relative w-full sm:w-auto">
                <select
                  value={selectedCourse}
                  onChange={(e) => setSelectedCourse(e.target.value)}
                  className="pl-4 pr-4 py-2 border border-gray-200 rounded-lg appearance-none bg-white w-full"
                >
                  <option value="all">All Courses</option>
                  {lecturerCourses.map((course) => (
                    <option key={course.id} value={course.id}>
                      {course.title}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th
                  scope="col"
                  className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Student
                </th>
                <th
                  scope="col"
                  className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Courses
                </th>
                <th
                  scope="col"
                  className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Progress
                </th>
                <th
                  scope="col"
                  className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Engagement
                </th>
                {/* <th
                  scope="col"
                  className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider"
                >
                  Actions
                </th> */}
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredStudents.map((student) => (
                <tr key={student.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="flex-shrink-0">
                        <div className="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center">
                          <UsersIcon className="w-5 h-5 text-gray-600" />
                        </div>
                      </div>
                      <div className="ml-4">
                        <div className="text-sm font-medium text-gray-900">
                          {student.firstName} {student.lastName}
                        </div>
                        <div className="text-sm text-gray-600">
                          {student.email}
                        </div>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="text-sm text-gray-600">
                      {student.enrollments.length} courses
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-16 bg-gray-200 rounded-full h-2 mr-2">
                        <div
                          className={`h-2 rounded-full ${
                            student.progress >= 90
                              ? "bg-green-500"
                              : student.progress >= 75
                              ? "bg-blue-500"
                              : "bg-yellow-500"
                          }`}
                          style={{
                            width: `${student.progress}%`,
                          }}
                        ></div>
                      </div>
                      <span className="text-sm text-gray-600">
                        {student.progress}%
                      </span>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-16 bg-gray-200 rounded-full h-2 mr-2">
                        <div
                          className={`h-2 rounded-full ${
                            student.engagement >= 90
                              ? "bg-green-500"
                              : student.engagement >= 75
                              ? "bg-blue-500"
                              : "bg-yellow-500"
                          }`}
                          style={{
                            width: `${student.engagement}%`,
                          }}
                        ></div>
                      </div>
                      <span className="text-sm text-gray-600">
                        {student.engagement}%
                      </span>
                    </div>
                  </td>
                  {/* <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <Link
                      href={`/dashboard/lecturer/students/${student.id}`}
                      className="text-blue-600 hover:text-blue-900"
                    >
                      View Profile
                    </Link>
                  </td> */}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
